name: Front Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Front Deployment
        run: echo Hello, world!

      - name: Front Deployment2
        run: |
          echo one line,
          echo two line