name: Front Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Github Actions...
        uses: actions/checkout@v3
    
      - name: Execute Remote SSH...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_FREE_MAIN_SSH_HOST }}
          username: ${{ secrets.ORACLE_FREE_MAIN_SSH_USER }}
          key: ${{ secrets.ORACLE_FREE_MAIN_SSH_PRIVATE_KEY }}
          port: ${{ secrets.ORACLE_FREE_MAIN_SSH_PORT }}
          script: |
            sudo su -
            cd /app/exhibit-world
            sudo git config --global --add safe.directory /app/exhibit-world
            sudo git pull origin main
            sudo export NODE_OPTIONS=--max_old_space_size=4096
            sudo npm run build
            sudo pm2 restart exhibit-world
            